---
title: "Statistical Inference Course Project"
output:
  pdf_document: default
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE)
```

##Set Parameters for exponential distribution and simulation
```{r GettingStarted}
lambda = .2
n = 40
sim = 10000
```

##Simulating the mean of a thousand trials

```{r Replication}
set.seed(1)
means = replicate(sim, expr = mean(rexp(n,lambda)))
```

##Theoretical Distribution Mean
```{r DistributionMean}
1/lambda
```
##Simulated Mean
```{r Simulated Mean}
mean(means)
```
As you can see the results are quite close

##Similarly
##Theoretical Variance
```{r Expected Variance}
1/lambda^2
```

```{r SimulatedVariance}
var(means)*n
```


```{r plot}
library(ggplot2)
ggplot(data.frame(means), aes(x=means, color="red")) + geom_density() + stat_function(fun = dnorm, aes(color = "blue"), arg = list(mean = 1/lambda, sd=sqrt(lambda^-2/n))) + scale_colour_manual("Legend title", values = c("red", "blue"), labels = c("Theoretical","Simulated"))+ggtitle("Comparison of Simulated Distribution to Theoretical Distribution")
```

##The confidence intervals of the mean estimate
```{r ConfidenceInterval}
mean(means) + c(-1,1)*sd(means)/sqrt(40)*qnorm(.975)
```



